<a href="https://colab.research.google.com/github/husthorng/ML/blob/main/NN31_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

horng@hust.edu.tw     https://chatgpt.com/c/6a920b27-8be4-83e8-8546-e1f94250b40a

In [ ]:
# ============================================================
# Neural Network 3-3-1
#
# Input  Layer : 3
# Hidden Layer : 3
# Output Layer : 1
#
# Activation : Sigmoid
# ============================================================

import numpy as np

# ============================================================
# 1. Training Data
# ============================================================

X = np.array([
    [0, 0, 1],
    [1, 0, 1],
    [1, 1, 1],
    [0, 1, 1]
], dtype=float)

Y = np.array([
    [0],
    [1],
    [1],
    [0]
], dtype=float)


# ============================================================
# 2. Sigmoid
# ============================================================

def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))


def sigmoid_derivative(x):
    return x * (1.0 - x)


# ============================================================
# 3. Initialize Weights
# ============================================================

np.random.seed(42)

# Input -> Hidden
# 3 Input × 3 Hidden
W0 = np.random.uniform(-1, 1, (3, 3))

# Hidden Bias
B0 = np.random.uniform(-1, 1, (1, 3))

# Hidden -> Output
# 3 Hidden × 1 Output
W1 = np.random.uniform(-1, 1, (3, 1))

# Output Bias
B1 = np.random.uniform(-1, 1, (1, 1))


# ============================================================
# 4. Training Parameters
# ============================================================

learning_rate = 1.0
epochs = 30000


# ============================================================
# 5. Neural Network Training
# ============================================================

for epoch in range(epochs):

    # --------------------------------------------------------
    # Forward propagation
    # --------------------------------------------------------

    # Input -> Hidden
    hidden_input = np.dot(X, W0) + B0

    hidden_output = sigmoid(hidden_input)

    # Hidden -> Output
    output_input = np.dot(hidden_output, W1) + B1

    output = sigmoid(output_input)


    # --------------------------------------------------------
    # Error
    # --------------------------------------------------------

    error = Y - output


    # --------------------------------------------------------
    # Backpropagation
    # --------------------------------------------------------

    # Output layer
    output_delta = error * sigmoid_derivative(output)


    # Hidden layer
    hidden_error = np.dot(output_delta, W1.T)

    hidden_delta = hidden_error * sigmoid_derivative(hidden_output)


    # --------------------------------------------------------
    # Update weights
    # --------------------------------------------------------

    W1 += np.dot(hidden_output.T, output_delta) * learning_rate

    B1 += np.sum(
        output_delta,
        axis=0,
        keepdims=True
    ) * learning_rate


    W0 += np.dot(X.T, hidden_delta) * learning_rate

    B0 += np.sum(
        hidden_delta,
        axis=0,
        keepdims=True
    ) * learning_rate


    # --------------------------------------------------------
    # Display loss
    # --------------------------------------------------------

    if epoch % 5000 == 0:

        loss = np.mean(np.square(error))

        print(
            "Epoch =", epoch,
            "Loss =", loss
        )


# ============================================================
# 6. Final Prediction
# ============================================================

print("\n==========================================")
print("TRAINING COMPLETE")
print("==========================================")

print("\nInput:")
print(X)

print("\nTarget:")
print(Y)

print("\nPrediction:")
print(output)


# ============================================================
# 7. Convert Prediction to 0 / 1
# ============================================================

prediction_binary = (output >= 0.5).astype(int)

print("\nPrediction Binary:")
print(prediction_binary)


# ============================================================
# 8. Accuracy
# ============================================================

accuracy = np.mean(prediction_binary == Y) * 100

print("\nAccuracy = %.2f%%" % accuracy)


# ============================================================
# 9. Print W0
# ============================================================

print("\n==========================================")
print("W0 : Input -> Hidden")
print("==========================================")

print(W0)


# ============================================================
# 10. Print B0
# ============================================================

print("\n==========================================")
print("B0 : Hidden Bias")
print("==========================================")

print(B0)


# ============================================================
# 11. Print W1
# ============================================================

print("\n==========================================")
print("W1 : Hidden -> Output")
print("==========================================")

print(W1)


# ============================================================
# 12. Print B1
# ============================================================

print("\n==========================================")
print("B1 : Output Bias")
print("==========================================")

print(B1)


# ============================================================
# 13. ESP32 Code
# ============================================================

print("\n\n==========================================")
print("ESP32 CODE")
print("==========================================")

print("\n// Input -> Hidden")

print("const float W0[3][3] = {")

for i in range(3):

    row = ", ".join(
        f"{W0[i][j]:.8f}f"
        for j in range(3)
    )

    print(f"  {{ {row} }},")

print("};")


print("\n// Hidden Bias")

print("const float B0[3] = {")

row = ", ".join(
    f"{B0[0][i]:.8f}f"
    for i in range(3)
)

print(f"  {row}")

print("};")


print("\n// Hidden -> Output")

print("const float W1[3] = {")

row = ", ".join(
    f"{W1[i][0]:.8f}f"
    for i in range(3)
)

print(f"  {row}")

print("};")


print("\n// Output Bias")

print(
    f"const float B1 = {B1[0][0]:.8f}f;"
)

Epoch = 0 Loss = 0.334838250176027
Epoch = 5000 Loss = 5.5820671323380516e-05
Epoch = 10000 Loss = 2.5989046278089946e-05
Epoch = 15000 Loss = 1.6733284851558767e-05
Epoch = 20000 Loss = 1.2274360584846287e-05
Epoch = 25000 Loss = 9.66387935653114e-06

TRAINING COMPLETE

Input:
[[0. 0. 1.]
 [1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]]

Target:
[[0.]
 [1.]
 [1.]
 [0.]]

Prediction:
[[0.00309485]
 [0.99744567]
 [0.99742794]
 [0.00301689]]

Prediction Binary:
[[0]
 [1]
 [1]
 [0]]

Accuracy = 100.00%

W0 : Input -> Hidden
[[ 5.16072098  4.54948892 -2.6330358 ]
 [-0.159771   -0.43525596 -0.38073619]
 [-1.94294369 -0.22277917  0.48123846]]

B0 : Hidden Bias
[[-0.64296576 -1.91396247  1.21882814]]

W1 : Hidden -> Output
[[ 6.35261101]
 [ 5.11806168]
 [-3.7771917 ]]

B1 : Output Bias
[[-3.56650693]]


ESP32 CODE

// Input -> Hidden
const float W0[3][3] = {
  { 5.16072098f, 4.54948892f, -2.63303580f },
  { -0.15977100f, -0.43525596f, -0.38073619f },
  { -1.94294369f, -0.22277917f, 0.48123846f },
};

// 