<a href="https://colab.research.google.com/github/husthorng/ML/blob/main/NN32_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


```
X1,X2,X3,Y1,Y2,
0,0,0,0,0,
0,1,0,0,0,
0,0,1,0,0,
0,1,1,0,0,
1,0,0,1,0,馬達轉  手臂不動
1,1,0,1,0,馬達轉  手臂不動
1,0,1,0,0,馬達不轉  手臂不動
1,1,1,0,1,馬達不轉  手臂動
```


https://docs.google.com/spreadsheets/d/1_21BAmcUZPho_3fz5_nwZR7xIjNchTdQKhTGtAIhi6s/edit?gid=1983589369#gid=1983589369!

horng@hust.edu.tw     https://chatgpt.com/c/6a920b27-8be4-83e8-8546-e1f94250b40a

In [ ]:
# ============================================================
# 115husthorng@ma327
# Neural Network 3-5-2
# Input  : 3
# Hidden : 5
# Output : 2
#
# X -> W0 -> Hidden -> W1 -> Output
#
# ============================================================

import numpy as np

np.random.seed(42)


# ============================================================
# 1. Training Data
# ============================================================

X = np.array([
    [0,0,0],
    [0,1,0],
    [0,0,1],
    [0,1,1],
    [1,0,0],
    [1,1,0],
    [1,0,1],
    [1,1,1]
], dtype=float)


Y = np.array([
    [0,0],
    [0,0],
    [0,0],
    [0,0],
    [1,0],
    [1,0],
    [0,0],
    [0,1]
], dtype=float)


# ============================================================
# 2. Sigmoid
# ============================================================

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_derivative(x):
    return x * (1 - x)


# ============================================================
# 3. Network Size
# ============================================================

INPUT_SIZE = 3
HIDDEN_SIZE = 5
OUTPUT_SIZE = 2


# ============================================================
# 4. Initialize Weights
# ============================================================

W0 = np.random.uniform(
    -1, 1,
    (INPUT_SIZE, HIDDEN_SIZE)
)

W1 = np.random.uniform(
    -1, 1,
    (HIDDEN_SIZE, OUTPUT_SIZE)
)


# ============================================================
# 5. Bias
# ============================================================

B0 = np.zeros((1, HIDDEN_SIZE))

B1 = np.zeros((1, OUTPUT_SIZE))


# ============================================================
# 6. Training Parameters
# ============================================================

learning_rate = 1.0

epochs = 100000


# ============================================================
# 7. Training
# ============================================================

for epoch in range(epochs):

    # --------------------------------------------------------
    # Forward
    # --------------------------------------------------------

    hidden_input = np.dot(X, W0) + B0

    hidden_output = sigmoid(hidden_input)


    output_input = np.dot(hidden_output, W1) + B1

    output = sigmoid(output_input)


    # --------------------------------------------------------
    # Error
    # --------------------------------------------------------

    error = Y - output


    # --------------------------------------------------------
    # Backpropagation
    # --------------------------------------------------------

    output_delta = (
        error *
        sigmoid_derivative(output)
    )


    hidden_error = np.dot(
        output_delta,
        W1.T
    )


    hidden_delta = (
        hidden_error *
        sigmoid_derivative(hidden_output)
    )


    # --------------------------------------------------------
    # Update W1
    # --------------------------------------------------------

    W1 += (
        np.dot(
            hidden_output.T,
            output_delta
        )
        * learning_rate
    )


    # --------------------------------------------------------
    # Update W0
    # --------------------------------------------------------

    W0 += (
        np.dot(
            X.T,
            hidden_delta
        )
        * learning_rate
    )


    # --------------------------------------------------------
    # Update Bias
    # --------------------------------------------------------

    B1 += (
        np.sum(
            output_delta,
            axis=0,
            keepdims=True
        )
        * learning_rate
    )


    B0 += (
        np.sum(
            hidden_delta,
            axis=0,
            keepdims=True
        )
        * learning_rate
    )


    # --------------------------------------------------------
    # Display training progress
    # --------------------------------------------------------

    if epoch % 10000 == 0:

        mse = np.mean(error ** 2)

        print(
            "Epoch:",
            epoch,
            "MSE:",
            mse
        )


# ============================================================
# 8. Final Prediction
# ============================================================

print("\n==========================================")
print("TRAINING COMPLETE")
print("==========================================")


print("\nInput X:")
print(X)


print("\nTarget Y:")
print(Y)


print("\nNeural Network Output:")
print(np.round(output, 6))


print("\nBinary Output:")
print(
    (output >= 0.5).astype(int)
)


# ============================================================
# 9. Check Every Training Data
# ============================================================

print("\n==========================================")
print("TEST RESULT")
print("==========================================")


for i in range(len(X)):

    print(
        "Input:",
        X[i].astype(int),
        " Target:",
        Y[i].astype(int),
        " Output:",
        np.round(output[i], 4),
        " Result:",
        (output[i] >= 0.5).astype(int)
    )


# ============================================================
# 10. Print W0
# ============================================================

print("\n==========================================")
print("W0 : INPUT -> HIDDEN")
print("Shape:", W0.shape)
print("==========================================")

print(W0)


# ============================================================
# 11. Print B0
# ============================================================

print("\n==========================================")
print("B0 : HIDDEN BIAS")
print("Shape:", B0.shape)
print("==========================================")

print(B0)


# ============================================================
# 12. Print W1
# ============================================================

print("\n==========================================")
print("W1 : HIDDEN -> OUTPUT")
print("Shape:", W1.shape)
print("==========================================")

print(W1)


# ============================================================
# 13. Print B1
# ============================================================

print("\n==========================================")
print("B1 : OUTPUT BIAS")
print("Shape:", B1.shape)
print("==========================================")

print(B1)


# ============================================================
# 14. ESP32 FORMAT
# ============================================================

print("\n\n")
print("==========================================")
print("ESP32 WEIGHT FORMAT")
print("==========================================")


# ============================================================
# W0
# ============================================================

print("\n// Input -> Hidden")

print("const float W0[3][5] = {")

for i in range(3):

    print("  {", end="")

    for j in range(5):

        print(
            f"{W0[i][j]:.8f}",
            end=""
        )

        if j < 4:
            print(", ", end="")

    print("}", end="")

    if i < 2:
        print(",")

print("\n};")


# ============================================================
# B0
# ============================================================

print("\n// Hidden Bias")

print("const float B0[5] = {")

for i in range(5):

    print(
        f"  {B0[0][i]:.8f}",
        end=""
    )

    if i < 4:
        print(", ", end="")

print("\n};")


# ============================================================
# W1
# ============================================================

print("\n// Hidden -> Output")

print("const float W1[5][2] = {")

for i in range(5):

    print("  {", end="")

    for j in range(2):

        print(
            f"{W1[i][j]:.8f}",
            end=""
        )

        if j < 1:
            print(", ", end="")

    print("}", end="")

    if i < 4:
        print(",")

print("\n};")


# ============================================================
# B1
# ============================================================

print("\n// Output Bias")

print("const float B1[2] = {")

for i in range(2):

    print(
        f"  {B1[0][i]:.8f}",
        end=""
    )

    if i < 1:
        print(", ", end="")

print("\n};")

Epoch: 0 MSE: 0.19893997566813715
Epoch: 10000 MSE: 2.5080578538480845e-05
Epoch: 20000 MSE: 1.1709106061278611e-05
Epoch: 30000 MSE: 7.561942330997554e-06
Epoch: 40000 MSE: 5.560783984714212e-06
Epoch: 50000 MSE: 4.38702952347598e-06
Epoch: 60000 MSE: 3.617166511378267e-06
Epoch: 70000 MSE: 3.074103856296328e-06
Epoch: 80000 MSE: 2.6708855497271233e-06
Epoch: 90000 MSE: 2.3598817611540057e-06

TRAINING COMPLETE

Input X:
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 1.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 0. 1.]
 [1. 1. 1.]]

Target Y:
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]
 [0. 1.]]

Neural Network Output:
[[1.04900e-03 1.00000e-06]
 [8.53000e-04 9.51000e-04]
 [1.20000e-05 8.00000e-06]
 [7.00000e-06 1.41600e-03]
 [9.98026e-01 2.90000e-05]
 [9.98185e-01 1.81300e-03]
 [7.93000e-04 1.80800e-03]
 [2.12000e-03 9.96807e-01]]

Binary Output:
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [0 0]
 [0 1]]

TEST RESULT
Input: [0 0 0]  Target: [0 0]  Output: [0.001 0.   ]  Result: [0 0